### ISSUE TITLE
Error generating lily58 image

### ISSUE THREAD

**Issue by mpardalos** [MrMarble/zmk-viewer#11]
I am getting the following error when trying to generate an image for my lily58 config.

```
❯ zmk-viewer generate lily58
2023-01-29T14:36:53Z INF Fetching keyboard layout.
zmk-viewer: error: invalid character '<' looking for beginning of value
```

I get the same error for other variations of the lily58 from the qmk configurator:

- zmk-viewer generate "splitkb/aurora/lily58/rev1"
- zmk-viewer generate "lily58/light"
- zmk-viewer generate "lily58/rev1"

It is also the same whether I add in my config with `-f` or not.

**Comment by MrMarble** [comment]
That error was because there isn't a keyboard named lily58 in the QMK repository and the request was giving a 404 error: https://keyboards.qmk.fm/v1/keyboards/lily58/info.json

The correct name includes the revision (lily58/rev1): https://keyboards.qmk.fm/v1/keyboards/lily58/rev1/info.json but I was replacing the `/` with `_` so it was broken...
I've added an error message to let the user know the keyboard isn't found instead of just an error, and removed the "sanitizing" for the name. The new release should be available soon

**Comment by mpardalos** [comment]
Awesome! Thanks!
